# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [1]:

# Создаем массив 10x10 со случайными значениями
array = np.random.rand(10, 10)

# Находим минимум и максимум
minimum = np.min(array)
maximum = np.max(array)

print("Массив:")
print(array)
print("Минимальное значение:", minimum)
print("Максимальное значение:", maximum)

Массив:
[[0.1498509  0.77685322 0.4993585  0.45108401 0.55405986 0.1992617
  0.69373343 0.74818274 0.30941192 0.48528375]
 [0.20961292 0.912772   0.58235999 0.84226484 0.53276468 0.80626464
  0.29118885 0.78298428 0.92386795 0.98755714]
 [0.99808998 0.06400031 0.20246801 0.5121654  0.40469293 0.00618246
  0.26428301 0.30938306 0.14046511 0.0586083 ]
 [0.73725596 0.75983422 0.64972326 0.4630679  0.73207141 0.98450642
  0.89526603 0.99105449 0.07185493 0.07564622]
 [0.25514281 0.61813163 0.34757861 0.56523225 0.06320943 0.43747276
  0.65989929 0.35678353 0.23602233 0.05741011]
 [0.89206144 0.67686638 0.13294723 0.66360454 0.94751128 0.90541434
  0.1580211  0.35169482 0.95788584 0.71730547]
 [0.49963984 0.54431569 0.32444212 0.2792896  0.13427082 0.06560701
  0.02601953 0.43251726 0.64735076 0.43172676]
 [0.78629787 0.82396437 0.94870405 0.48232829 0.8170953  0.21419479
  0.96118046 0.87066134 0.95095914 0.59042065]
 [0.66231583 0.17610529 0.89151376 0.68479824 0.78233066 0.78107346
  0.5

2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [2]:


# Создаем 8x8 матрицу заполненную нулями
chessboard = np.zeros((8, 8))

# Заполняем матрицу в шахматном порядке
chessboard[1::2, ::2] = 1  # Заполнение единицами для чёрных клеток
chessboard[::2, 1::2] = 1  # Заполнение единицами для белых клеток

print(chessboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [3]:


z = np.arange(11)

print("Исходный массив:")
print(z)

# Меняем знак у элементов, значения которых находятся между 3 и 8 (не включая 8)
z[(z > 3) & (z < 8)] *= -1

print("Массив после изменения знака элементов между 3 и 8:")
print(z)

Исходный массив:
[ 0  1  2  3  4  5  6  7  8  9 10]
Массив после изменения знака элементов между 3 и 8:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [4]:

z = np.random.rand(5, 10)

print("Исходная матрица:")
print(z)

# Находим среднее значение каждой строки
mean_values = np.mean(z, axis=1)

# Вычитаем средние значения из каждой строки
z_centered = z - mean_values[:, np.newaxis]

print("\nМатрица после вычитания средних значений из каждой строки:")
print(z_centered)

Исходная матрица:
[[0.69523799 0.62915661 0.90407963 0.40714358 0.97151588 0.35001588
  0.66143742 0.64910163 0.61050412 0.08342679]
 [0.41743343 0.23618252 0.00769886 0.56835304 0.47783301 0.87606608
  0.45519116 0.23107706 0.22031149 0.71252064]
 [0.4661565  0.40721976 0.80738646 0.59374597 0.44561003 0.17028898
  0.94682948 0.87086171 0.72479986 0.6137993 ]
 [0.25523245 0.40740009 0.50678743 0.59553121 0.23099237 0.0583462
  0.97119163 0.33453296 0.8288365  0.75081933]
 [0.22878829 0.61364647 0.19321597 0.57881093 0.639296   0.48753294
  0.40824895 0.03461902 0.96079228 0.87377216]]

Матрица после вычитания средних значений из каждой строки:
[[ 0.09907604  0.03299466  0.30791768 -0.18901837  0.37535392 -0.24614607
   0.06527547  0.05293968  0.01434216 -0.51273517]
 [-0.00283329 -0.18408421 -0.41256787  0.14808631  0.05756628  0.45579935
   0.03492443 -0.18918967 -0.19995524  0.29225392]
 [-0.13851331 -0.19745004  0.20271666 -0.01092384 -0.15905977 -0.43438082
   0.34215967  0.266191

5. Поменяйте 1 и 2 строки матрицы

In [5]:


# Создаем матрицу 5x5
z = np.arange(25).reshape(5, 5)

print("Исходная матрица:")
print(z)

# Меняем местами первую и вторую строки
z[[0, 1]] = z[[1, 0]]

print("\nМатрица после замены первой и второй строк:")
print(z)

Исходная матрица:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Матрица после замены первой и второй строк:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [6]:
z = np.random.random((10, 2)) * 10  # Умножаем на 10 для большей разброса

print("Декартовые координаты:")
print(z)

# Извлекаем x и y
x = z[:, 0]
y = z[:, 1]

# Вычисляем радиусы и углы
r = np.sqrt(x**2 + y**2)        # Радиус
theta = np.arctan2(y, x)        # Угол в радианах

# Объединяем результаты в один массив
polar_coordinates = np.column_stack((r, theta))

print("\nПолярные координаты (r, θ):")
print(polar_coordinates)

Декартовые координаты:
[[1.60124056 9.0716885 ]
 [9.97037081 6.74544049]
 [0.67788545 7.53452117]
 [4.43229932 5.61178637]
 [6.3286984  9.83094014]
 [9.28679429 1.566634  ]
 [5.75657584 6.49602315]
 [1.51128445 8.28055755]
 [1.11088343 5.83602435]
 [3.7066368  1.99374902]]

Полярные координаты (r, θ):
[[ 9.21192182  1.39608625]
 [12.03782628  0.59481278]
 [ 7.56495459  1.48106731]
 [ 7.15104353  0.9022938 ]
 [11.69186929  0.99882513]
 [ 9.41800883  0.16712136]
 [ 8.6796591   0.8456753 ]
 [ 8.41734008  1.39027324]
 [ 5.94081158  1.38269723]
 [ 4.20882306  0.49349529]]


7. Заменить максимальный элемент массива на ноль

In [7]:
z = np.random.random(10)

print("Исходный массив:")
print(z)

# Нахождение индекса максимального элемента
max_index = np.argmax(z)

# Замена максимального элемента на 0
z[max_index] = 0

print("\nМассив после замены максимального элемента на 0:")
print(z)

Исходный массив:
[0.42423322 0.16060092 0.12754546 0.05248927 0.77234101 0.57639501
 0.03720181 0.70199256 0.18695955 0.04000505]

Массив после замены максимального элемента на 0:
[0.42423322 0.16060092 0.12754546 0.05248927 0.         0.57639501
 0.03720181 0.70199256 0.18695955 0.04000505]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [8]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
# Используем np.unique для получения уникальных индексов
unique_indices = np.unique(i)

# Добавляем 1 к элементам массива z по уникальным индексам
z[unique_indices] += 1

print("Исходный массив z:")
print(z)
print("\nСгенерированные индексы:")
print(unique_indices)

Исходный массив z:
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]

Сгенерированные индексы:
[0 1 2 3 4 5 6 7 8 9]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [9]:
z = np.array([1,2,3,4,5])
# Определяем количество нулей между значениями
num_zeros = 3

# Создаем новый вектор с учетом количества нулей
new_length = len(z) + (len(z) - 1) * num_zeros
new_vector = np.zeros(new_length)

# Заполняем новый вектор значениями из z
new_vector[::num_zeros + 1] = z

print("Новый вектор с тремя нулями между значениями:")
print(new_vector)

Новый вектор с тремя нулями между значениями:
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [10]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
# Нахождение ближайшего значения в массиве z
closest_value = z[np.abs(z - v).argmin()]

print("Случайное значение v:", v)
print("Ближайшее значение в массиве z:", closest_value)

Случайное значение v: 16.42475780048396
Ближайшее значение в массиве z: 16


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?