# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [5]:
import numpy as np
x=np.random.randint(1, 50, (10, 10))
print(x)
print(np.max(x))
print(np.min(x))

[[29 47 43 44 49 43 26 12 38  3]
 [ 2  1 46 37 34  2 18 19 40 49]
 [27 14 22 26 32 45 48 31 46 27]
 [20  6 22 39 40 14 11 46 36 21]
 [28 38  6 44 19 28 13  7 17 21]
 [47 16 42  9 35 35 47 26  5  3]
 [28 11 42 22 26 36 23 13 27  5]
 [ 2 35 48  7 23  6 32 20 26 28]
 [10 31 15 23 30 41 36 28 12 14]
 [23 16 29 27 41 38 24 23 24 45]]
49
1


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [6]:
x=np.zeros((8,8))
x[0::2, 0::2] = 1
x[1::2, 1::2] = 1
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [7]:
z = np.arange(11)
z[3:8]*=-1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [8]:
z = np.random.rand(5, 10)
print(z)
sr=np.mean(z)
print(sr)
z=z-sr
print(z)

[[0.08402106 0.14811896 0.47181616 0.02320802 0.37436962 0.44070344
  0.22504276 0.02877297 0.43255393 0.21731607]
 [0.73124434 0.08948701 0.35669739 0.99266238 0.70723294 0.10589119
  0.68217638 0.83863929 0.61791546 0.11495614]
 [0.65292244 0.8640806  0.97871333 0.91001101 0.49456024 0.19531154
  0.94740434 0.55040473 0.1498016  0.05270606]
 [0.34585234 0.08606536 0.34975519 0.84423428 0.81308636 0.68851064
  0.40135604 0.94668652 0.07286224 0.11415468]
 [0.70843757 0.81297098 0.92204875 0.75373529 0.19876718 0.12910004
  0.98885382 0.01934302 0.42335312 0.84959726]]
0.4789502415362943
[[-0.39492918 -0.33083128 -0.00713408 -0.45574222 -0.10458062 -0.0382468
  -0.25390748 -0.45017728 -0.04639632 -0.26163417]
 [ 0.2522941  -0.38946323 -0.12225285  0.51371214  0.2282827  -0.37305905
   0.20322614  0.35968905  0.13896521 -0.3639941 ]
 [ 0.1739722   0.38513036  0.49976309  0.43106077  0.01560999 -0.2836387
   0.4684541   0.07145448 -0.32914864 -0.42624418]
 [-0.1330979  -0.39288488 -0.129

5. Поменяйте 1 и 2 строки матрицы

In [9]:
z = np.arange(25).reshape(5,5)
z[[0,1]]=z[[1,0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [10]:
z = np.random.random((10,2))
print(z)
x,y = z[:,0], z[:,1]
a = np.hypot(x, y)
b = np.arctan2(y,x)
print(a)
print(b)

[[0.8512138  0.43796751]
 [0.6262081  0.25223574]
 [0.24717088 0.83959416]
 [0.97632867 0.35211284]
 [0.15802107 0.54883005]
 [0.43697665 0.94485201]
 [0.061188   0.15305463]
 [0.92243464 0.83538499]
 [0.96922814 0.98228501]
 [0.9884285  0.65071143]]
[0.95727764 0.67509959 0.875221   1.037883   0.57112615 1.0410062
 0.16483231 1.24448935 1.37995907 1.18339185]
[0.47519693 0.38291662 1.28449121 0.3461308  1.29045538 1.13761133
 1.19048063 0.73591721 0.7920887  0.58220834]


7. Заменить максимальный элемент массива на ноль

In [11]:
z = np.random.random(10)
maxim=np.argmax(z)
print(z)
z[maxim]=0
print(z)

[0.61522369 0.94201155 0.5187257  0.02493707 0.8177465  0.41471102
 0.96973675 0.53443317 0.28432887 0.94906779]
[0.61522369 0.94201155 0.5187257  0.02493707 0.8177465  0.41471102
 0.         0.53443317 0.28432887 0.94906779]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [12]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print(z)
print(i)
z += np.bincount(i, minlength=len(z))
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 0 3 7 8 1 0 9 9 5 8 5 6 8 1 5 3 0 9 6]
[4. 3. 1. 4. 1. 4. 3. 2. 4. 4.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [13]:
z = np.array([1,2,3,4,5])
lens = 5 + (5 - 1) * 3
z1 = np.zeros(lens)
z1[::4] = z
print(z)
print(z1)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [14]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
print(z)
print(v)
x=z[np.abs(z-v).argmin()]
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
71.15314749101393
71


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

*   dtype: int64;
*   dtype: float64. присутствует число с плавающей запятой (1.), поэтому все числа будут приведены к этому типу;
*  dtype: float128. Явно указанный тип массива – float128;
*  dtype: complex128.Явно указанный тип массива - complex128;
*  dtype: float64. Явно указанный тип массива – float64;
*  dtype: int64. Явно указанный тип массива - int64;
*  dtype: bool. Все целые числа будут преобразованы в логические значения;
*  dtype: str. Все целые числа будут преобразованы в строки
*  dtype: str. Поскольку в массиве присутствует строковое значение;
*  dtype: complex128. Поскольку в массиве присутствует комплексное число;


**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

*   Вывод: 41. Берется массив строковых значений, к 1ому элементу добавляется строка со значением '1';
*   Вывод: True. Третий элемент первого массива = 0 = True, первый элемент второго массива = -4 = False. True or False = True;
*   Вывод: False. Третий элемент первого массива = 0 = True. Первый элемент второго массива = -4 = False. True and False = False
*   Вывод: 1. -1 элемент массива = True. Значение True принимает 1;
*   Вывод: ошибка. Комплексное число не может быть преобразовано в int64;
*   Вывод: 1j. Комплексное число преобразуется в строку;
*   Вывод: 333. Умножение строки - ее повторение n количество раз;

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



*   Результат: массив формы (3, 5), заполненный единицами;
*   Результат: массив формы (3, 5), заполненный значением 3.14.;
*   Результат:
```
array([0. , 0.25, 0.5 , 0.75, 1. ])
```
*   Результат:
```
array([[1, 0, 0],
          [0, 3, 0],
          [0, 0, 5]])
```
*   Результат: ошибка, функции не существует;
*   Результат: массив формы (3, 3) с случайными числами;
*   Результат: создает единичную матрицу размером 3x3, где элементы на главной диагонали равны единице, а остальные — нулю
*   Результат: создает массив формы (3,) с неинициализированными значениями

**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

*   3;
*   7;
*   array([4]) - срез первой строки и последнего элемента в столбце;
*   array([4, 8]) - срез первых двух строк и их последних элементов;
*   
```
array([[3, 5],
          [7, 6]])
```
*   array([6, 8])
*   array([7, 6, 8, 8])
*   array([7, 6, 8, 8])
*   
```
array([[3, 5, 2, 4],
          [7, 6, 8, 8],
          [1, 6, 7, 7]])
```
*   элементы с интервалом 2 по обеим осям:
```
 array([[3, 2],
           [1, 7]])
```
*   
```
 array([[3, 2],
           [1, 7]])
```

*   Реверс строк и столбцов, поэтому массив будет перевернут:
```
    array([[7, 6, 1],
           [8, 6, 7],
           [4, 2, 5]])
```


**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


Первая операция  разбивает массив по строкам (ось 0).Вторая операция с параметром axis=1 разбивает массив по столбцам (ось 1):


```
  [array([[0, 1, 2, 3],
           [4, 5, 6, 7]]),
    array([[ 8,  9, 10, 11],
           [12, 13, 14, 15]])]
           
    [array([[0, 1],
           [4, 5],
           [8, 9],
           [12, 13]]),
    array([[ 2, 3],
           [ 6, 7],
           [10, 11],
           [14, 15]])].
```

**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

При работе NumPy массивами производится поэлементное сложение, после чего создается новый массив, состоящий из суммы соответствующих элементов. При работе с обычными списками создается новый список с элементами, указанными при сложении:


```
[1, 2, 3, 3, 2, 1]
array([4, 4, 4])
```

**7**. Как в CodeLab измерить время выполнения кода?

Использование модуля time.


```
import time

start_time = time.time()
.....
end_time = time.time()
print(end_time - start_time)
```


**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

*   63;
*   Сумма элементов по строкам: [14,29,21];
*   Сумма элементов по столбцам: [11,17,17,19];
*   Ошибка, т.к массив 3х4;
*   [14,29,21];
*   array([3,5,2,4]);
*   array([3,5,2,4]);

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

*   [False, False, False, True];
*   [True, True, False, False];
*   [1, 2];
*   [4];
*   [1,2,4];

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

На уровне реализации массив фактически содержит один указатель на непрерывный блок данных. Список в языке Python же содержит указатель на блок указателей, каждый из которых, в свою очередь, указывает на целый объект языка Python, например, целое число. Преимущество такого списка состоит в его гибкости: раз каждый элемент списка — полномасштабная структура, содержащая как данные, так и информацию о типе, список можно заполнить данными любого требуемого типа. Массивам с фиксированным типом из библиотеки NumPy недостает этой гибкости, но они гораздо эффективнее хранят данные и работают с ними.