<a href="https://colab.research.google.com/github/golodenko2209/dap-2024/blob/main/les03/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'1.26.4'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
x = np.random.rand(10, 10)
print(x)
print(np.min(x))
print(np.max(x))

[[0.66041256 0.73099247 0.78721709 0.052117   0.57749202 0.56041296
  0.24921428 0.69332529 0.98427884 0.7701989 ]
 [0.83754876 0.56451786 0.23766222 0.80305853 0.59143538 0.36357411
  0.31868188 0.57782022 0.12441408 0.38450191]
 [0.21058008 0.94684575 0.84696742 0.93360684 0.85477431 0.21058833
  0.84566107 0.89506982 0.49879523 0.91934131]
 [0.38669358 0.3874283  0.5537556  0.56681827 0.76846221 0.06482638
  0.88256763 0.77619537 0.32512714 0.25424187]
 [0.155551   0.03541367 0.34819792 0.41961203 0.35728616 0.02073914
  0.56435201 0.77793048 0.43697844 0.65934447]
 [0.28292442 0.46382237 0.03369035 0.27678364 0.70291403 0.0728216
  0.33785385 0.97650984 0.22152303 0.3088134 ]
 [0.10714361 0.86206412 0.54026685 0.55607461 0.29734656 0.70871838
  0.0592327  0.36329628 0.54249239 0.35712037]
 [0.38727923 0.0352858  0.26539965 0.82061523 0.13645252 0.57002148
  0.40667534 0.01416149 0.01228373 0.30266442]
 [0.6709475  0.81640264 0.08559828 0.33874272 0.2346213  0.12553781
  0.37662319 

2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:
x = np.zeros((8, 8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
z = np.arange(11)
print(z)
z[(z > 3) & (z < 8)] *= -1
z

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
z = np.arange(0, 50).reshape(5, 10)
print(z)
rowz = np.mean(z, axis = 1)
print(rowz)
colz = rowz.reshape(5, 1)
print(colz)
z - colz

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 4.5 14.5 24.5 34.5 44.5]
[[ 4.5]
 [14.5]
 [24.5]
 [34.5]
 [44.5]]


array([[-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5]])

5. Поменяйте 1 и 2 строки матрицы

In [ ]:
z = np.arange(25).reshape(5,5)
print(z)
(z[0], z[1]) = (z[1], z[0].copy())
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
z = np.random.random((10,2))
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(np.power(x, 2) + np.power(y, 2))
f = np.arctan(y, x)
pol = np.concatenate([r.reshape(10, 1), f.reshape(10, 1)], axis = 1)
pol

array([[0.05845442, 0.04032491],
       [0.7697099 , 0.15060694],
       [0.47803975, 0.28609086],
       [0.69899067, 0.59517941],
       [0.97118265, 0.21211199],
       [1.03412007, 0.69507697],
       [1.1043221 , 0.74866317],
       [0.6991756 , 0.31205523],
       [1.03796369, 0.77615397],
       [0.9367317 , 0.07908612]])

7. Заменить максимальный элемент массива на ноль

In [ ]:
z = np.random.random(10)
print(z)
maxz = np.argmax(z)
z[maxz] = 0
z

[3.19598382e-01 6.71009616e-01 3.86515713e-02 7.05186113e-04
 5.22647229e-01 3.89627065e-01 6.92474923e-01 1.10754364e-01
 7.75416608e-01 7.87562842e-01]


array([3.19598382e-01, 6.71009616e-01, 3.86515713e-02, 7.05186113e-04,
       5.22647229e-01, 3.89627065e-01, 6.92474923e-01, 1.10754364e-01,
       7.75416608e-01, 0.00000000e+00])

8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print(z)
z.flat[i] += 1
z

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([2., 2., 2., 2., 2., 2., 2., 2., 1., 2.])

9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
z = np.array([1,2,3,4,5])
zn = np.zeros(len(z) + (len(z)-1)*3)
zn[::4] = z
zn

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
print(v)
index = np.argmin(np.abs(z - v))
nv = z[index]
nv

14.982676399140471


15

## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?