<a href="https://colab.research.google.com/github/mihail1707/dap-2024/blob/main/les03/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'1.26.4'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
# Напишите ваш код здесь
arr = np.random.random((10,10))
print(arr)
min, max = arr.min(), arr.max()
print("min", min)
print("max", max)

[[0.03786687 0.92245341 0.41679784 0.08040307 0.597289   0.62039274
  0.60905425 0.29575746 0.62348435 0.66391688]
 [0.78997049 0.46239589 0.34696962 0.80422499 0.10015754 0.09982592
  0.48392502 0.07024749 0.02209167 0.89675345]
 [0.72504051 0.61150188 0.92614218 0.55915734 0.62250531 0.4201836
  0.67369655 0.40472115 0.35804483 0.68696768]
 [0.99319898 0.27178521 0.67615642 0.606298   0.37147292 0.8591357
  0.72050639 0.94858855 0.54319104 0.51125321]
 [0.12985218 0.77369617 0.58755559 0.78493431 0.99836515 0.8445814
  0.8495341  0.99845687 0.33110396 0.85865462]
 [0.85463455 0.10849866 0.92171794 0.20134666 0.95777044 0.56113156
  0.05372733 0.79921962 0.48242112 0.49451396]
 [0.41390123 0.53730847 0.28721143 0.71090799 0.18756329 0.1495134
  0.92408674 0.16728073 0.21126665 0.27905414]
 [0.38478806 0.63135526 0.32634323 0.70469544 0.81208146 0.59445042
  0.02638114 0.61577009 0.89947656 0.77696307]
 [0.32191179 0.70250902 0.77581189 0.63348421 0.47405721 0.43851198
  0.69968501 0.7

2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:
# Напишите ваш код здесь
matrix = np.zeros((8,8), dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
z = np.arange(11)
# Напишите ваш код здесь
z[(3 < z) & (z <= 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
z = np.random.rand(5, 10)
# Напишите ваш код здесь
print(z)
row_means = np.mean(z, axis=1)
res = z - row_means[:, np.newaxis]
print("\n",row_means,"\n")
print(res)

[[0.40618802 0.94642377 0.27940369 0.80298023 0.4362061  0.40906701
  0.44186605 0.46610794 0.49957382 0.36851715]
 [0.52697309 0.26278674 0.19123274 0.24791413 0.22565817 0.70706916
  0.27900399 0.8738695  0.52691179 0.48461934]
 [0.48795343 0.02566259 0.40279978 0.7564821  0.13155458 0.12617003
  0.5298661  0.77173167 0.66842034 0.85653115]
 [0.23217331 0.2378641  0.52547849 0.12413926 0.66031457 0.01061321
  0.94603318 0.67792968 0.14468685 0.5464148 ]
 [0.85360206 0.41286189 0.33908602 0.09541479 0.30279661 0.27713255
  0.00614385 0.37195386 0.77484147 0.50052705]]

 [0.50563338 0.43260386 0.47571718 0.41056474 0.39343602] 

[[-0.09944536  0.44079039 -0.22622969  0.29734685 -0.06942727 -0.09656636
  -0.06376733 -0.03952544 -0.00605956 -0.13711623]
 [ 0.09436923 -0.16981713 -0.24137112 -0.18468974 -0.20694569  0.27446529
  -0.15359988  0.44126564  0.09430793  0.05201548]
 [ 0.01223625 -0.45005459 -0.07291739  0.28076492 -0.3441626  -0.34954715
   0.05414893  0.2960145   0.19270316  

5. Поменяйте 1 и 2 строки матрицы

In [ ]:
z = np.arange(25).reshape(5,5)
# Напишите ваш код здесь
z[[0, 1]] = z[[1, 0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
z = np.random.random((10,2))
# Ваш код здесь
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.hypot(x, y)
t = np.arctan2(y,x)
print(r)
print(t)

[0.24377473 0.68753973 0.25077192 1.14763924 0.71939746 0.66476696
 0.93232975 0.33945909 0.36251008 0.76706553]
[0.58145571 0.27060648 1.40346455 0.61613863 0.72941063 0.50647498
 1.02131784 0.90855825 0.23340461 1.24638329]


7. Заменить максимальный элемент массива на ноль

In [ ]:
z = np.random.random(10)
# Ваш код здесь

z[z.argmax()] = 0
print(z)

[0.35937327 0.36929735 0.43801576 0.11207095 0.23306759 0.20441196
 0.31964276 0.49869378 0.         0.1310596 ]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
z = np.ones(10)

i = np.random.randint(0,len(z),20)

# Напишите ваш код здесь
z += np.bincount(i, minlength=len(z))
print(z)

[1. 3. 2. 3. 3. 3. 3. 2. 5. 5.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
z = np.array([1,2,3,4,5])
# Напишите ваш код здесь
nz = 3
z0 = np.zeros(len(z) + (len(z)-1)*(nz))
z0[::nz+1] = z
print(z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
# Напишите ваш код здесь
index = (np.abs(z-v)).argmin()
print(z[index])

41


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?