<a href="https://colab.research.google.com/github/Russia31/dap-2024/blob/main/les03/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
import numpy as np
x=np.random.randint(1, 100, (10, 10))
print(x)
print(np.max(x))
print(np.min(x))

Ответ:[[40 87 59 37 48 76 99 41 81 51]

 [98 19 17 14 10 14 88 87 55 60]

 [50 82 34 61 68 25 74 48 19 43]

 [90 54 64 59 44 81 17 76 25 25]

 [30 96 18 37 73  6 78  1 40 23]

 [96  5 22 62 60 17 51 34 92 24]

 [79 75  2 25 25 43 17  7 66 79]

 [98 84 16  8 10 76 12 53 61 92]

 [49 15 56 10 26 50 91 65 91 83]

 [30 49 65 47 32 78 84 45 35 34]]

99

1


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:
import numpy as np
x=np.zeros((8,8))
x[0::2, 0::2] = 1
x[1::2, 1::2] = 1
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]

 [0. 1. 0. 1. 0. 1. 0. 1.]

 [1. 0. 1. 0. 1. 0. 1. 0.]

 [0. 1. 0. 1. 0. 1. 0. 1.]

 [1. 0. 1. 0. 1. 0. 1. 0.]

 [0. 1. 0. 1. 0. 1. 0. 1.]

 [1. 0. 1. 0. 1. 0. 1. 0.]

 [0. 1. 0. 1. 0. 1. 0. 1.]]

3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
import numpy as np
z = np.arange(11)
z[3:8]*=-1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]



4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
import numpy as np
z = np.random.rand(5, 10)
print(z)
sr=np.mean(z)
print(sr)
z=z-sr
print(z)

[[0.98716534 0.73434322 0.50633695 0.39101841 0.19419039 0.06639497
  0.12426281 0.31422622 0.66950633 0.19616812]

 [0.4870844  0.65645545 0.59579583 0.97523425 0.49936984 0.81018571
  0.10589335 0.26768015 0.44729746 0.70480573]
  
   [0.8366336  0.53093428 0.01062627 0.95383183 0.77630526 0.58098995
  0.43690785 0.91506911 0.28441606 0.54825546]

 [0.64485454 0.84117458 0.21056639 0.86846733 0.73046356 0.06571702
  0.0259436  0.90257397 0.91435781 0.18454883]

 [0.40894019 0.71647918 0.07806086 0.82012071 0.85287076 0.98907368
  0.49479763 0.49501952 0.45127781 0.45341742]]
0.5351222001269896

[  [ 0.45204314  0.19922102 -0.02878525 -0.14410379 -0.34093181 -0.46872723
  -0.41085939 -0.22089598  0.13438413 -0.33895408]

 [-0.0480378   0.12133325  0.06067363  0.44011205 -0.03575236  0.27506351
  -0.42922885 -0.26744206 -0.08782474  0.16968353]

 [ 0.3015114  -0.00418792 -0.52449593  0.41870963  0.24118306  0.04586774
  -0.09821435  0.37994691 -0.25070614  0.01313326]

 [ 0.10973234  0.30605238 -0.32455581  0.33334513  0.19534136 -0.46940518
  -0.5091786   0.36745177  0.37923561 -0.35057337]

 [-0.12618201  0.18135698 -0.45706134  0.28499851  0.31774856  0.45395148
  -0.04032457 -0.04010268 -0.08384439 -0.08170478]]

5. Поменяйте 1 и 2 строки матрицы

In [ ]:
import numpy as np
z = np.arange(25).reshape(5,5)
z[[0,1]]=z[[1,0]]
print(z)

[[ 5  6  7  8  9]

 [ 0  1  2  3  4]

 [10 11 12 13 14]

 [15 16 17 18 19]

 [20 21 22 23 24]]

6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
import numpy as np
z = np.random.random((10,2))
print(z)
x,y = z[:,0], z[:,1]
a = np.hypot(x, y)
b = np.arctan2(y,x)
print(a)
print(b)

[[0.56158776 0.74732166]

 [0.67659179 0.01200333]

 [0.84041641 0.82789379]

 [0.3669869  0.44977315]

 [0.62453406 0.54221153]

 [0.86391463 0.4626313 ]

 [0.12544344 0.02866769]

 [0.25071698 0.61941349]

 [0.9453455  0.69839573]

 [0.40269796 0.47843578]]

[0.93481039 0.67669825 1.17970669 0.58049571 0.82706477 0.97998786
 0.12867748 0.66823056 1.17534451 0.62535305]

[0.92635683 0.01773902 0.77789214 0.88641251 0.71495751 0.49164717
 0.22467258 1.18618885 0.63627702 0.87114238]

7. Заменить максимальный элемент массива на ноль

In [ ]:
import numpy as np
z = np.random.random(10)
maxim=np.argmax(z)
print(z)
z[maxim]=0
print(z)

[0.02202948 0.96114588 0.31485687 0.56452426 0.22525178 0.8800752
 0.82980479 0.0669179  0.92099256 0.74823879]

[0.02202948 0.         0.31485687 0.56452426 0.22525178 0.8800752
 0.82980479 0.0669179  0.92099256 0.74823879]

8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print(z)
print(i)
z += np.bincount(i, minlength=len(z))
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[0 0 7 6 5 4 0 9 9 3 5 8 2 4 8 8 1 9 3 5]

[4. 2. 2. 3. 3. 4. 2. 2. 4. 4.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
import numpy as np
z = np.array([1,2,3,4,5])
lens = 5 + (5 - 1) * 3
z1 = np.zeros(lens)
z1[::4] = z
print(z)
print(z1)

[1 2 3 4 5]

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
import numpy as np
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
print(z)
print(v)
x=z[np.abs(z-v).argmin()]
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

47.6199566412624

48

## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

1) np.array([1, 4, 2, 5, 3])
Тип: int64 (или int32, в зависимости от платформы).

2) np.array([1., 4, 2, 5, 3])
Тип: float64 (все элементы преобразуются в тип float).

3) np.array([1, 4, 2, 5, 3], dtype='float128')
Тип: float128 (если поддерживается на платформе).

4) np.array([1., 4, 2, 5, 3], dtype='complex128')
Тип: complex128 (все элементы становятся комплексными).

5) np.array([1, 4, 2, 5, 3], dtype ='float64')
Тип: float64 (все элементы будут преобразованы в тип float64).

6) np.array([1, 4, 2, 5, 3], dtype =int64)
Тип: int64.

7) np.array([1, 4, 2, 5, 3], dtype='bool')
Тип: bool (все элементы будут преобразованы в булевы значения: True или False).

8) np.array([1, 4, 2, 5, 3], dtype='str')
Тип: str (все элементы становятся строками).

9) np.array([1, 4, 2, 5, '3'])
Тип: str (массив будет приведен к строковому типу, так как встречается строковый элемент).

10) np.array([1, -4, 2, 0, 1j])
Тип: complex128 (включение комплексного числа заставляет весь массив быть комплексным).

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

1. np.array([1, 4, 2, 5, 3], dtype='str')
[1] + '1'
Вывод: '41'. Элемент с индексом 1 — строка '4', и добавляется строка '1'.

2. np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
Вывод: True. Операция or между False (элемент с индексом 3) и True (элемент с индексом 1) вернет True.

3. np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
Вывод: False. Операция and между False (элемент с индексом 3) и True (элемент с индексом 1) вернет False.

4. np.array([1, -4, 2, 0, True], dtype='int64')[-1]
Вывод: 1. Значение True преобразуется в 1.

5. np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
Ошибка: невозможно привести комплексное число 1j к целочисленному типу.

6. np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
Вывод: '1j'. Преобразование комплексного числа в строку.

7. np.array([1, 4, 2, 5, '3'])[-1] * 3
Вывод: '333'. Последний элемент — строка '3', умноженная на 3.

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



1. массив размером (3, 5), заполненный единицами типа float64.

2. массив размером (3, 5), заполненный значением 3.14.

3. массив из 5 равномерно распределенных значений от 0 до 1.

4. диагональная матрица с элементами 1, 3, 5.

5. np.smile не существует в библиотеке numpy.

6. массив (3, 3) с случайными значениями от 0 до 1.

7. единичная матрица размером (3, 3).

8. массив размером 3 с неинициализированными значениями (мусорные данные).

**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

1. 3
 Это элемент в первой строке и первом столбце.

2. 7
 Это последний элемент (последняя строка и последний столбец).

3. [4]. Это первая строка и последний столбец.

4. [4, 8]. Это первые две строки и последний столбец.

5. [[3 5]
 [7 6]]

6. [6 8]. Это вторая строка, начиная с индекса 1 и до индекса 3.

7. [7, 6, 8, 8]. Это вся вторая строка.

8. [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
Это весь массив.

9. [[3 2]
 [1 7]]
Это каждая вторая строка и каждый второй столбец.

10. [[3 2]
 [1 7]]
Это каждую вторую строку и столбец от первого до третьего.

11. [[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]
Это массив, перевернутый по строкам и столбцам.



**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


* np.split(grid, [2])
Разделяет массив grid на два массива по строкам, начиная с индекса 2:

      [array([[ 0,  1,  2,  3],

              [ 4,  5,  6,  7]]),

       array([[ 8,  9, 10, 11],

              [12, 13, 14, 15]])]

* np.split(grid, [2], axis=1)
Разделяет массив по столбцам, начиная с индекса 2:

      [array([[ 0,  1],
              [ 4,  5],
              [ 8,  9]]),
      array([[ 2,  3],
             [ 6,  7],
             [10, 11]]),
      array([[12, 13],
             [14, 15]])]

**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

1. [1, 2, 3] + [3, 2, 1]
Это операция сложения списков. Результат:
[1, 2, 3, 3, 2, 1]


2. np.array([1, 2, 3]) + np.array([3, 2, 1])
Это операция поэлементного сложения массивов NumPy. Результат:
[4, 4, 4]

**7**. Как в CodeLab измерить время выполнения кода?

Для измерения времени выполнения кода в CodeLab можно использовать модуль time или timeit:

Используя time:

      import time
      start_time = time.time()

      print(f"Время выполнения: {time.time() - start_time} секунд")
Используя timeit:

      import timeit
      print(timeit.timeit('Ваш код', number=1000))

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

54

[14,29,21]

[11, 17, 17, 19]

Ошибка. Так как X — это двумерный массив, нельзя суммировать по оси 2.

Ошибка. Так как X — это двумерный массив, нельзя суммировать по оси 2.

Это стандартная функция Python для суммирования, которая будет работать для списков, но не для массивов NumPy.

Это стандартная функция Python для суммирования, которая будет работать для списков, но не для массивов NumPy.

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

[False False False  True]

[ True  True False False]

[1 2]

[4]

[1 2 4]

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

1. Производительность: Массивы NumPy значительно быстрее списков Python благодаря оптимизированным операциям с данными и векторизации.

2. Меньше памяти: Массивы NumPy занимают меньше памяти, чем списки Python, поскольку используют более компактное представление данных.

3. Векторизация: NumPy поддерживает векторные операции, которые позволяют выполнять математические операции поэлементно над большими массивами без использования циклов.

4. Работа с многомерными данными: NumPy предоставляет удобные структуры для работы с многомерными массивами (матрицами и т.д.), чего нет в стандартных списках Python.