# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [2]:
import numpy as np
array = np.random.randint(0, 100, size=(10, 10))
minimum = np.min(array)
maximum = np.max(array)
print("Массив 10x10:")
print(array)
print(f"Минимум: {minimum}")
print(f"Максимум: {maximum}")


Массив 10x10:
[[30 21 84  9 50 49 35 51 72 36]
 [95 62  6  3 91 94 78 21 64 53]
 [89 98  5 38 54 64 41  3 13 29]
 [ 4 53 64 96 92 68 13 30 14 97]
 [68 59 49 99 79 11 74  5 28 18]
 [30 84 34 69 36 52 70 99 15 17]
 [38 66 38 33 13 81 46 33 44 72]
 [53 73 72 82 35 42 73 26 85 75]
 [51 30 49 14 49 98 34 74  0 76]
 [92 34 69 45 58 56 58 61 23 51]]
Минимум: 0
Максимум: 99


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [3]:
import numpy as np
matrix = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            matrix[i, j] = 1
print("8x8 матрица в шахматном порядке:")
print(matrix)

8x8 матрица в шахматном порядке:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [4]:
import numpy as np
z = np.arange(11)
print("Исходный массив z:")
print(z)
for i in range(len(z)):
    if 3 < z[i] < 8:
        z[i] = -z[i]
print("Измененный массив z:")
print(z)


Исходный массив z:
[ 0  1  2  3  4  5  6  7  8  9 10]
Измененный массив z:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [5]:
import numpy as np
z = np.random.rand(5, 10)
print("Исходная матрица z:")
print(z)
mean_values = np.mean(z, axis=1)
z_centered = z - mean_values[:, np.newaxis]
print("\nМатрица после вычитания среднего значения из каждой строки:")
print(z_centered)

Исходная матрица z:
[[0.58849575 0.6276213  0.7394143  0.40421205 0.49424968 0.14126678
  0.8792042  0.43696739 0.03641954 0.03431903]
 [0.11526545 0.79387823 0.61402654 0.43352933 0.61369312 0.13445391
  0.64448193 0.25492656 0.08188043 0.12472412]
 [0.81439634 0.34490489 0.17006328 0.46163956 0.38350374 0.66379891
  0.38597747 0.0984073  0.59544551 0.56243232]
 [0.13171377 0.42361258 0.03525227 0.54242778 0.83965402 0.581547
  0.72773653 0.75926974 0.02054075 0.85403168]
 [0.19469547 0.19154407 0.76057194 0.49030557 0.5809964  0.09235597
  0.51496629 0.34326663 0.8381159  0.73048451]]

Матрица после вычитания среднего значения из каждой строки:
[[ 0.15027874  0.1894043   0.3011973  -0.03400495  0.05603268 -0.29695022
   0.4409872  -0.00124961 -0.40179746 -0.40389797]
 [-0.26582051  0.41279227  0.23294057  0.05244337  0.23260716 -0.24663205
   0.26339597 -0.12615941 -0.29920553 -0.25636184]
 [ 0.36633941 -0.10315204 -0.27799365  0.01358263 -0.06455319  0.21574198
  -0.06207946 -0.3496

5. Поменяйте 1 и 2 строки матрицы

In [6]:
import numpy as np
z = np.arange(25).reshape(5, 5)
print("Исходная матрица z:")
print(z)
z[[0, 1]] = z[[1, 0]]
print("\nМатрица после замены 1 и 2 строк:")
print(z)

Исходная матрица z:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Матрица после замены 1 и 2 строк:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [7]:
import numpy as np
z = np.random.random((10, 2))
print("Исходные декартовы координаты (x, y):")
print(z)
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coordinates = np.column_stack((r, theta))
print("\nПолярные координаты (r, θ):")
print(polar_coordinates)


Исходные декартовы координаты (x, y):
[[0.94395323 0.85516069]
 [0.93898997 0.07443106]
 [0.37095168 0.27238885]
 [0.82768065 0.5599809 ]
 [0.8325443  0.97257219]
 [0.27363762 0.3165751 ]
 [0.16716187 0.98526847]
 [0.38799712 0.54919648]
 [0.16816695 0.82636546]
 [0.05446591 0.01634262]]

Полярные координаты (r, θ):
[[1.27371406 0.73608469]
 [0.94193532 0.07910175]
 [0.46021825 0.63337546]
 [0.9993167  0.59482498]
 [1.28024477 0.86281589]
 [0.41844634 0.8580194 ]
 [0.99934831 1.40273544]
 [0.67242735 0.95573363]
 [0.84330303 1.37003582]
 [0.0568649  0.29150482]]


7. Заменить максимальный элемент массива на ноль

In [8]:
import numpy as np
z = np.random.random(10)
print("Исходный массив z:")
print(z)
max_index = np.argmax(z)
z[max_index] = 0
print("\nМассив после замены максимального элемента на 0:")
print(z)

Исходный массив z:
[0.76796644 0.63075235 0.30856696 0.800048   0.67703184 0.42644132
 0.31959367 0.74460757 0.33332884 0.84546528]

Массив после замены максимального элемента на 0:
[0.76796644 0.63075235 0.30856696 0.800048   0.67703184 0.42644132
 0.31959367 0.74460757 0.33332884 0.        ]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [9]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
print("Исходный массив z:")
print(z)
print("\nСлучайные индексы i:")
print(i)
unique_indices = np.unique(i)
z[unique_indices] += 1
print("\nМассив z после добавления 1 к элементам по заданным индексам:")
print(z)


Исходный массив z:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Случайные индексы i:
[5 8 3 7 0 4 0 8 4 7 9 1 8 0 4 3 0 7 1 3]

Массив z после добавления 1 к элементам по заданным индексам:
[2. 2. 1. 2. 2. 2. 1. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [10]:
import numpy as np
z = np.array([1, 2, 3, 4, 5])
print("Исходный вектор:")
print(z)
new_vector = np.zeros(len(z) + (len(z) - 1) * 3, dtype=z.dtype)
new_vector[::4] = z
print("\nНовый вектор с тремя нулями между каждым значением:")
print(new_vector)

Исходный вектор:
[1 2 3 4 5]

Новый вектор с тремя нулями между каждым значением:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [11]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0, 100)
print("Случайное число v:", v)
closest_value = z[np.abs(z - v).argmin()]
print("Ближайшее значение в массиве z:", closest_value)


Случайное число v: 17.578550361298937
Ближайшее значение в массиве z: 18


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?