<a href="https://colab.research.google.com/github/VladissPM/pythonLessonFork/blob/main/les03/LabWork3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лабораторная работа №3. NumPy
##Задания
1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [12]:
import numpy as np
z = np.random.random((10, 10))
min_val = z.min()
max_val = z.max()
print(z)
print(min_val)
print(max_val)

[[0.58503019 0.27033088 0.21390403 0.05581874 0.01525371 0.40218822
  0.82759484 0.72401447 0.40269349 0.28551515]
 [0.67450847 0.35370571 0.18344569 0.19939636 0.34439616 0.36911691
  0.09768666 0.7812319  0.74019678 0.29633528]
 [0.39727112 0.2379251  0.65565809 0.13814605 0.27251696 0.96923272
  0.29944462 0.49362871 0.96812173 0.87691152]
 [0.43236727 0.07955746 0.54321551 0.45833377 0.8112506  0.90405473
  0.53868155 0.643163   0.60343945 0.21170072]
 [0.03356576 0.53422856 0.02371191 0.99233532 0.6807769  0.20116716
  0.83608671 0.2572779  0.4110529  0.96414583]
 [0.11845182 0.83786056 0.2003025  0.00295834 0.22574294 0.32340153
  0.99499578 0.24550243 0.57267171 0.27615536]
 [0.0926624  0.73543506 0.05412383 0.38310459 0.7508231  0.94724782
  0.35253428 0.14892624 0.20818788 0.20753606]
 [0.34732625 0.0404804  0.91440981 0.05184199 0.69549379 0.09795977
  0.79022265 0.61752504 0.31128902 0.0100536 ]
 [0.36654379 0.50243009 0.16889366 0.13938181 0.09380467 0.31154587
  0.65250745

2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [13]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [14]:
import numpy as np
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [15]:
z = np.random.rand(5, 10)
z -= z.mean(axis=1, keepdims=True)
print(z)

[[-0.45464983  0.14681799  0.00950134  0.43245519  0.15147766  0.24589787
   0.11125962 -0.48592932 -0.45437355  0.29754303]
 [-0.31572536  0.22462202  0.19096239  0.41643094  0.32644483 -0.33054069
   0.13969325 -0.20847866 -0.1781479  -0.26526081]
 [-0.0219489   0.00260937  0.13784743  0.02715908  0.02572094 -0.11363787
  -0.19780798  0.0972192  -0.11557335  0.15841209]
 [ 0.23245084  0.35873136 -0.05763193 -0.38236001  0.05258898  0.10255872
  -0.4262717   0.09859101  0.0062946   0.01504814]
 [-0.3303561   0.27186285 -0.25736616  0.19031088 -0.12670561 -0.38737027
   0.11890235  0.45353289  0.34314352 -0.27595434]]


5. Поменяйте 1 и 2 строки матрицы

In [17]:
z = np.arange(25).reshape(5, 5)
z[[0, 1]] = z[[1, 0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [16]:
z = np.random.random((10, 2))
r = np.sqrt(z[:, 0]**2 + z[:, 1]**2)
theta = np.arctan2(z[:, 1], z[:, 0])
print(theta)

[0.46163606 0.46539377 1.20251071 0.67575729 0.76351222 0.77462803
 0.8492773  0.4486905  0.83104689 1.05988619]


7. Заменить максимальный элемент массива на ноль

In [18]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.18482369 0.77541806 0.41984539 0.07113617 0.40997106 0.73094769
 0.         0.5000981  0.64574743 0.29813704]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [19]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
z[i] += 1
z = np.clip(z, 0, 2)  # Добавление только 1 раз
print(z)

[2. 2. 2. 1. 2. 2. 2. 2. 1. 1.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [21]:
z = np.array([1, 2, 3, 4, 5])
z_new = np.zeros(len(z) * 4 - 3)
z_new[::4] = z
print(z)

[1 2 3 4 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [20]:
z = np.arange(100)
v = np.random.uniform(0, 100)
closest_value = z[np.abs(z - v).argmin()]
print(closest_value)

30
