<a href="https://colab.research.google.com/github/BogdanType/dap-2024/blob/main/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Отчет о выполненной работе (лаб.3)
##Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы> <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request


In [2]:
import numpy as np
np.version.version

'1.26.4'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [6]:
import numpy as np
array = np.random.randint(1, 100, (10, 10))
print("\nСозданный массив: \n\n", array)
print("\nМинимальное значение:", array.min())
print("Максимальное значение:", array.max())


Созданный массив: 

 [[85 89 99 97 89 21 66 41 46 49]
 [35 41 31 15 14 38 64  3 83 90]
 [12 57 75 29 61  6 90 85 12 49]
 [64 19 39 88 38 30 50 36 47  2]
 [ 3 52 33  9 12 65 17 60 34 20]
 [26 39  7 17 48 33 98 30 86 50]
 [26 29 87 94 71  8 40 58 23 82]
 [60  1 24 57 92 57 29 62 34 78]
 [ 8 35 61 46 18 85 93 68 75  6]
 [86 72 40 66  1 27 44 69 17 15]]

Минимальное значение: 1
Максимальное значение: 99


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [7]:
import numpy as np
matrix = np.zeros((8,8))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print("Матрица 8х8 в шахматном порядке: \n", matrix)

Матрица 8х8 в шахматном порядке: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [11]:
import numpy as np
x = np.arange(11)
print("Исходный массив:\n", x)
x[(x > 3) & (x < 8)] *= -1
print("\nИзмененный массив:\n", x)

Исходный массив:
 [ 0  1  2  3  4  5  6  7  8  9 10]

Измененный массив:
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [23]:
import numpy as np
z = np.random.rand(5, 10)
print("Матрица: \n", z)
means = np.mean(z, axis=1, keepdims=True)
z[:, :9] -= means
print("\nСреднее значение:\n", means)
print("\nИзмененная матрица:\n", z)

Матрица: 
 [[0.34495814 0.83727564 0.3235312  0.97878224 0.74341575 0.65115462
  0.3644011  0.84078471 0.03900457 0.25469785]
 [0.49249687 0.42855589 0.34107987 0.34664327 0.44291776 0.66470474
  0.60063353 0.24177101 0.95155017 0.40523528]
 [0.58731166 0.48874748 0.40454518 0.50535747 0.31651688 0.89041133
  0.01131215 0.92231832 0.97684435 0.086347  ]
 [0.19534509 0.13844346 0.06825883 0.33626517 0.52722119 0.66227509
  0.69185147 0.43540708 0.02414976 0.02385278]
 [0.75044046 0.76307598 0.33202835 0.30606908 0.54925737 0.57396406
  0.29178898 0.73325456 0.2494987  0.78141059]]

Среднее значение:
 [[0.53780058]
 [0.49155884]
 [0.51897118]
 [0.31030699]
 [0.53307881]]

Измененная матрица:
 [[-0.19284245  0.29947506 -0.21426938  0.44098166  0.20561517  0.11335404
  -0.17339948  0.30298412 -0.49879602  0.25469785]
 [ 0.00093803 -0.06300295 -0.15047897 -0.14491557 -0.04864108  0.1731459
   0.10907469 -0.24978783  0.45999133  0.40523528]
 [ 0.06834048 -0.0302237  -0.114426   -0.01361371 -

5. Поменяйте 1 и 2 строки матрицы

In [14]:
import numpy as np
z = np.arange(25).reshape(5,5)
print("Матрица:\n", z)
z[[1, 2]] = z[[2, 1]]
print("\nИзмененная матрица:\n", z)

Матрица:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Измененная матрица:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [24]:
import numpy as np
z = np.random.random((10, 2))
print("Декартова система координат:\n", z)
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
phi = np.arctan2(y, x)
pz = np.column_stack((r, phi))
print("\nПолярные координаты:\n", pz)

Декартова система координат:
 [[0.02424196 0.30088379]
 [0.74902647 0.39839636]
 [0.30870816 0.26149599]
 [0.80839804 0.68117104]
 [0.91693478 0.102198  ]
 [0.47027955 0.2057255 ]
 [0.2512386  0.71484294]
 [0.52033938 0.25432932]
 [0.97777371 0.64025533]
 [0.52541406 0.29255434]]

Полярные координаты:
 [[0.30185878 1.4904008 ]
 [0.84838689 0.48882949]
 [0.40457493 0.70278789]
 [1.05711937 0.70019301]
 [0.9226125  0.11099801]
 [0.51330872 0.41237153]
 [0.7577079  1.23282155]
 [0.57916878 0.45462803]
 [1.16874647 0.57974868]
 [0.60137174 0.50805446]]


 7. Заменить максимальный элемент массива на ноль

In [25]:
import numpy as np
z = np.random.random(10)
print("Массив:\n", z)
max = np.argmax(z)
print("\nИндекс максимального элемента:", max)
z[max] = 0
print("\nИзмененный массив:\n", z)

Массив:
 [0.78816781 0.79330728 0.89559086 0.83076708 0.26067994 0.57920418
 0.96009053 0.85497223 0.13195195 0.85986307]

Индекс максимального элемента: 6

Измененный массив:
 [0.78816781 0.79330728 0.89559086 0.83076708 0.26067994 0.57920418
 0.         0.85497223 0.13195195 0.85986307]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [17]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print("Массив:\n", z)
print("\nМассив индексов:\n", i)
unique = np.unique(i)
z[unique] += 1
print("\nИзмененный массив:\n", z)

Массив:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Массив индексов:
 [4 8 6 2 8 3 5 8 9 2 8 8 6 1 4 6 5 3 3 9]

Измененный массив:
 [1. 2. 2. 2. 2. 2. 2. 1. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [18]:
import numpy as np
z = np.array([1,2,3,4,5])
print("Вектор:\n", z)
x = np.zeros(len(z) + (len(z) - 1) * 3)
x[::4] = z
print("\nНовый вектор:\n", x)

Вектор:
 [1 2 3 4 5]

Новый вектор:
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [20]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0,100)
print("Массив:\n", z)
print("\nЗаданное значение:", v)
x = np.fabs(z - v).argmin()
y = z[x]
print("\nБлижайшее значение для", v, "=", y)

Массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Заданное значение: 17.381149639071005

Ближайшее значение для 17.381149639071005 = 17
