# **Лабораторная работа №3. Библиотека NumPy**

**Цель работы:** Научиться основным элементам библиотеки NumPy и их применению в решении задач

## Ход работы

## Задача №1

In [1]:
# Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)
import numpy as np

# Генерирует матрицу 10x10 с элементами в диапазоне от 1 до 10 включительно
x = np.random.randint(1, 11, size=[10, 10])
print(F"MIN: {np.min(x)}, MAX: {np.max(x)}")
print("MATRIX:\n", x)


MIN: 1, MAX: 10
MATRIX:
 [[ 1  8  7  5  9  9  1  7  3  7]
 [ 7  8  4  5  9  6  4  7  9  3]
 [ 6  8  8  4  1  9  1  2  4 10]
 [ 3  2  8  1  3  8  5  5  9  6]
 [ 7  8  4  6  2  6  6  3  2  5]
 [10  5  9  7  3  2  9  6  2  4]
 [ 5  2  1  5  4  8  2  4  6  7]
 [ 1  2  4  8  3  3  5  5  2  9]
 [ 6  7  7  5  2  2  1  4  9 10]
 [ 4  2  9  8 10  3  4 10  4  5]]


## Задача №2

In [2]:
# Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке
import numpy as np

x = np.zeros((8, 8))
x[::2, ::2] = 1
x[1::2, 1::2] = 1
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


## Задача №3

In [3]:
# Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8
import numpy as np

z = np.arange(11)
z[(3 < z) & (z < 8)] *= -1
print(z)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## Задача №4

In [5]:
# Найти среднее значение строки матрицы и вычесть его из каждого элемента строки
import numpy as np

z = np.random.rand(5, 10)
print("Before:\n", z)
print("Mean for rows:\n", z.mean(1, keepdims=True))
z -= z.mean(1, keepdims=True)
print("After:\n", z)


Before:
 [[0.23856783 0.82084599 0.10638781 0.9796473  0.54653881 0.45888219
  0.63269449 0.6211541  0.13534915 0.39622575]
 [0.00118304 0.99147798 0.69084403 0.80363822 0.43673935 0.91580529
  0.92575499 0.41261646 0.48417389 0.62583086]
 [0.38112073 0.99908232 0.70159386 0.12347771 0.41179644 0.81271464
  0.95157484 0.73111849 0.69722373 0.20841768]
 [0.27361147 0.0599119  0.34114421 0.36663017 0.13587871 0.65882156
  0.13016173 0.93170861 0.08410356 0.52948499]
 [0.48227478 0.10278496 0.98121944 0.30231527 0.73657629 0.46716934
  0.08083952 0.45934743 0.97489237 0.89072228]]
Mean for rows:
 [[0.49362934]
 [0.62880641]
 [0.60181204]
 [0.35114569]
 [0.54781417]]
After:
 [[-0.25506151  0.32721665 -0.38724154  0.48601795  0.05290947 -0.03474715
   0.13906515  0.12752476 -0.35828019 -0.09740359]
 [-0.62762337  0.36267157  0.06203762  0.17483181 -0.19206706  0.28699888
   0.29694858 -0.21618995 -0.14463252 -0.00297555]
 [-0.22069132  0.39727027  0.09978181 -0.47833433 -0.1900156   0.21090

## Задача №5

In [6]:
# Поменяйте 1 и 2 строки матрицы
import numpy as np

z = np.arange(25).reshape(5, 5)
print("Before:\n", z)
z[[0, 1]] = z[[1, 0]]
# z[:2] = z[1::-1]
# z[0], z[1] = z[1].copy(), z[0].copy()
print("After:\n", z)


Before:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
After:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Задача №6

In [8]:
# Дан массив 10x2 представляющий собой точки в декартовой системе координат, преобразовать в полярную координату
import numpy as np

z = np.random.random((10, 2))
X = z[:, 0].copy()
Y = z[:, 1].copy()
print("Before:\n", z)
z[:, 0] = np.sqrt(pow(X, 2) + pow(Y, 2))
z[:, 1] = np.arctan2(Y, X)
print("After:\n", z)


Before:
 [[0.38738547 0.41928198]
 [0.90526671 0.12275599]
 [0.06156458 0.1380076 ]
 [0.09121506 0.98229056]
 [0.17930811 0.85973077]
 [0.09036226 0.92888223]
 [0.15384399 0.32788095]
 [0.58404733 0.83542399]
 [0.23349131 0.15951425]
 [0.7866582  0.76708253]]
After:
 [[0.57084576 0.82491866]
 [0.91355177 0.13477992]
 [0.15111682 1.15119407]
 [0.98651657 1.47820231]
 [0.87823026 1.36518075]
 [0.93326713 1.47382083]
 [0.36217936 1.13208529]
 [1.01933534 0.9606727 ]
 [0.28277728 0.59934111]
 [1.09874781 0.77279977]]


## Задача №7

In [9]:
# Заменить максимальный элемент массива на ноль
import numpy as np

z = np.random.random(10)
print(z)
print("Max:", z.max())
# z[z.argmax()] = 0 # Заменяет первое вхождение максимального элемента
z[z == z.max()] = 0  # Заменяем все максимальные элементы (если максимальный элемент встретился 2 раза)
print(z)


[0.19791158 0.32257377 0.10074366 0.39130897 0.15916664 0.1870422
 0.49545486 0.50717223 0.25214047 0.14141291]
Max: 0.5071722276952684
[0.19791158 0.32257377 0.10074366 0.39130897 0.15916664 0.1870422
 0.49545486 0.         0.25214047 0.14141291]


## Задача №8

In [10]:
# Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз
import numpy as np

z = np.ones(10)
i = np.random.randint(0, len(z), 20)
print(z, i)
z[i] += 1
print(z)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [3 8 3 0 5 6 6 5 8 8 7 6 8 5 6 5 7 3 4 1]
[2. 2. 1. 2. 2. 2. 2. 2. 2. 1.]


## Задача №9

In [11]:
# Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением
import numpy as np

z = np.array([1, 2, 3, 4, 5])
x = np.zeros((len(z) + (len(z) - 1) * 3), np.int64)
x[::4] = z
print(x)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


## Задача №10

In [12]:
# Найти ближайшее к заданному значению число в заданном массиве
import numpy as np

z = np.arange(100)  # Массив
v = np.random.randint(0, 100) # Число
print(z, v)
print(np.argwhere(z == v))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 39
[[39]]


# **Вывод:**
Научился основным элементам библиотеки NumPy и их применению в решении задач