<a href="https://colab.research.google.com/github/ill0wl/dap-2024/blob/main/les03/rep_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа 3

**Задание 1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)**

In [ ]:
import numpy as np
import random
np.version.version
random_2d_array = np.random.randint(1, 100, size=(10, 10))
print(f"Двумерный массив случайных чисел: \n{random_2d_array}")
min_value = random_2d_array[0][0]
max_value = random_2d_array[0][0]
for i in range(10):
    for j in range(10):
        if random_2d_array[i][j] < min_value:
            min_value = random_2d_array[i][j]
        if random_2d_array[i][j] > max_value:
            max_value = random_2d_array[i][j]
print(f"Минимальное значение: {min_value}")
print(f"Максимальное значение: {max_value}")

Двумерный массив случайных чисел: 
[[74 56 44 22 27 16 23 57 32 93]
 [26 96  7  7 47 72 31 57 95 23]
 [14 47  8 46 94 38 28 92 72 19]
 [23  5  6 35 51 62 57 94  4 60]
 [80 63 11 56 18 29 45 18 94 21]
 [68 16 80 57 40 67 65 93 13 13]
 [84 73 38 30 40 49 54 75 37 19]
 [20 49 17 28 30 57 60 63 64 94]
 [28 37  9 90 78 86 10 50 39 58]
 [54 79  6 74 23 97 65 64 39 12]]
Минимальное значение: 4
Максимальное значение: 97


**Задание 2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке**

In [ ]:
import numpy as np
import random
np.version.version
chech_array = np.zeros((8, 8))
print(f"Двумерный массив из нулей: \n{chech_array}")
chech_array[::2, ::2] = 1
chech_array[1::2, 1::2] = 1
print(f"Двумерный массив в шахматном порядке: \n{chech_array}")

Двумерный массив из нулей: 
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Двумерный массив в шахматном порядке: 
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**Задание 3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8**

In [ ]:
import numpy as np
np.version.version
z = np.arange(11)
print(f"Одномерный массив случайных чисел: \n{z}")
for i in range(11):
    if z[i] > 3 and z[i] < 8:
        z[i] = z[i] * (-1)
print(f"Одномерный массив чисел с измененными знаками: \n{z}")

Одномерный массив случайных чисел: 
[ 0  1  2  3  4  5  6  7  8  9 10]
Одномерный массив чисел с измененными знаками: 
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


**Задание 4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки**

In [ ]:
import numpy as np
z = np.random.rand(5, 10)
z_rounded = np.round(z,1)
print(f"Двумерный массив: \n{z_rounded}")
for i in range(5):
    sum = 0
    for j in range(10):
        sum += z[i][j]
        if j == 9:
            j = 0
            for j in range(10):
                z_rounded[i][j] = z_rounded[i][j] - sum
    print("-----", sum.round(1))

print(z_rounded.round(1))

Двумерный массив: 
[[0.6 0.3 0.6 0.9 0.7 0.6 0.6 0.3 0.  0.6]
 [0.4 0.2 0.2 0.9 0.6 0.2 0.4 0.  0.5 0.7]
 [0.9 0.6 0.3 0.8 0.2 0.5 0.6 0.  0.  0.4]
 [0.5 0.4 0.6 0.8 0.9 0.4 0.6 0.  0.2 0.7]
 [0.4 0.2 0.3 0.5 0.2 0.8 0.3 0.9 0.4 0.3]]
----- 5.3
----- 4.1
----- 4.3
----- 5.2
----- 4.3
[[-4.7 -5.  -4.7 -4.4 -4.6 -4.7 -4.7 -5.  -5.3 -4.7]
 [-3.7 -3.9 -3.9 -3.2 -3.5 -3.9 -3.7 -4.1 -3.6 -3.4]
 [-3.4 -3.7 -4.  -3.5 -4.1 -3.8 -3.7 -4.3 -4.3 -3.9]
 [-4.7 -4.8 -4.6 -4.4 -4.3 -4.8 -4.6 -5.2 -5.  -4.5]
 [-3.9 -4.1 -4.  -3.8 -4.1 -3.5 -4.  -3.4 -3.9 -4. ]]


**Задание 5. Поменяйте 1 и 2 строки матрицы**

In [ ]:
import numpy as np
z = np.arange(25).reshape(5,5)
print(z)
row_1 = z[1].copy()
row_0 = z[0].copy()
z[0] = row_1
z[1] = row_0
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**Задание 6. Дан массив 10x2 представлющий собой точки в декартовой системе координат, преобразовать в полярную**

Полярная система координат — двумерная система координат, в которой каждая точка на плоскости определяется двумя числами — полярным углом и полярным радиусом.

In [ ]:
import numpy as np
z = np.random.random((10,2))
print(z)
r = np.sqrt(z[:, 0]**2 + z[:, 1]**2)
ygol = np.arctan2(z[:, 1], z[:, 0])
polar = np.column_stack((r, ygol))
print(polar)

[[0.2238485  0.04716501]
 [0.48098764 0.26704081]
 [0.47914805 0.27001815]
 [0.44709587 0.76658263]
 [0.42963821 0.36808771]
 [0.88649895 0.05872174]
 [0.49672317 0.38329614]
 [0.429002   0.0358754 ]
 [0.62731644 0.62154317]
 [0.94531167 0.05720772]]
[[0.22876339 0.20766311]
 [0.55014534 0.50682116]
 [0.54999332 0.51317765]
 [0.88743656 1.04279715]
 [0.56575396 0.70839328]
 [0.88844169 0.06614343]
 [0.62741521 0.65721336]
 [0.43049943 0.08343113]
 [0.88308653 0.78077536]
 [0.94704111 0.0604436 ]]


**Задание 7. Заменить максимальный элемент массива на ноль Текст, выделенный полужирным шрифтом**

In [ ]:
import numpy as np
z = np.random.random(10)
max = z[0]
print(z)
for i in range(10):
    if z[i] > max:
        max = z[i]
print(f"Максимальное число {max}")
for i in range(10):
    if z[i] == max:
        z[i] = 0
        break
print(z)

[0.42390333 0.0292559  0.13357137 0.26378566 0.1074237  0.52521705
 0.0784729  0.82417587 0.92221765 0.882352  ]
Максимальное число 0.9222176536678826
[0.42390333 0.0292559  0.13357137 0.26378566 0.1074237  0.52521705
 0.0784729  0.82417587 0.         0.882352  ]


**Задание 8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз**

In [ ]:
import numpy as np
z = np.ones(10)
x = np.random.randint(0,len(z),20)
print(z)
print(x)
unique_x = np.unique(x)  # Убираем дубликаты
print(unique_x)
for i in unique_x:
    z[i] += 1
print(z)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6 7 7 7 2 4 6 6 5 4 3 4 0 3 0 1 0 1 4 6]
[0 1 2 3 4 5 6 7]
[2. 2. 2. 2. 2. 2. 2. 2. 1. 1.]


**Задание 9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением**

In [ ]:
import numpy as np
z = np.array([1,2,3,4,5])
rez = []
print(z)
for i in z:
     rez.extend([i, 0, 0, 0])
rez = rez[:-3]
print(rez)

[1 2 3 4 5]
[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


**Задание 10. Найти ближайшее к заданному значению число в заданном массиве**

In [ ]:
import numpy as np
z = np.arange(100) # Массив
v = np.random.uniform(0,100) # Число
print(z)
print(v)
value = abs(z[0]-v)
rez = 0
print(value)
for i in z:
    if abs(z[i] - v) < value:
        value = abs(z[i] - v)
        rez = z[i]
print(rez)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
2.8865896962756765
2.8865896962756765
3
