<a href="https://colab.research.google.com/github/pnmrVAA/dap-2024/blob/main/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
x=np.random.randint(1, 50, (10, 10))
print(x)
print(np.max(x))
print(np.min(x))

[[ 6 32 47 10  9 28 31 35 21 27]
 [13  8 32 37  3 41 46 43 12 31]
 [11 44 18 19 32 47 27 34  8 32]
 [ 8 23 40 16  7  7 32 28  9 19]
 [21 49 49 15 11  1  6 13  9 43]
 [19 32 20 22 43  2 22 10 33 46]
 [ 2 15 49 41  4 14 11 28 29  2]
 [41 31 33  4  3 15 17 48 42 19]
 [28 18 13 28 36 10 46 14 25 25]
 [27 37 49 18 46 40 25 15 24 47]]
49
1


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:

x=np.zeros((8,8))
x[0::2, 0::2] = 1
x[1::2, 1::2] = 1
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
z = np.arange(11)
z[3:8]*=-1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
z = np.random.rand(5, 10)
print(z)
sr=np.mean(z)
print(sr)
z=z-sr
print(z)

[[0.68369559 0.80936315 0.18882796 0.10695344 0.35758452 0.40654241
  0.96587218 0.77580562 0.51036479 0.61715649]
 [0.8953714  0.4679031  0.16950474 0.50940574 0.9944275  0.2208408
  0.64298987 0.42589431 0.24757149 0.76611593]
 [0.56914125 0.64089488 0.13476756 0.70217237 0.51566504 0.38501374
  0.76960962 0.175582   0.33013726 0.66696119]
 [0.41220229 0.57467843 0.24746057 0.41686464 0.79125319 0.80955888
  0.61523838 0.49220459 0.40015095 0.28205244]
 [0.93762861 0.62842476 0.99069662 0.19961785 0.43946889 0.91998785
  0.95134522 0.56720447 0.1727079  0.83881314]]
0.5467939123175828
[[ 0.13690167  0.26256924 -0.35796595 -0.43984047 -0.18920939 -0.1402515
   0.41907827  0.2290117  -0.03642913  0.07036258]
 [ 0.34857749 -0.07889081 -0.37728917 -0.03738817  0.44763359 -0.32595312
   0.09619596 -0.1208996  -0.29922242  0.21932202]
 [ 0.02234734  0.09410097 -0.41202635  0.15537846 -0.03112887 -0.16178017
   0.22281571 -0.37121191 -0.21665665  0.12016727]
 [-0.13459162  0.02788452 -0.299

5. Поменяйте 1 и 2 строки матрицы

In [ ]:
z = np.arange(25).reshape(5,5)
z[[0,1]]=z[[1,0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
z = np.random.random((10,2))
print(z)
x,y = z[:,0], z[:,1]
a = np.hypot(x, y)
b = np.arctan2(y,x)
print(a)
print(b)

[[0.39292262 0.0659882 ]
 [0.1485879  0.47315971]
 [0.93874356 0.81622254]
 [0.14465017 0.83709992]
 [0.70656281 0.27886276]
 [0.15104929 0.02958152]
 [0.92741356 0.25102206]
 [0.81317666 0.27191497]
 [0.99388148 0.85641474]
 [0.50432864 0.99820783]]
[0.39842519 0.49594201 1.24396894 0.84950571 0.75960216 0.15391866
 0.96078509 0.85743456 1.31196288 1.11837661]
[0.16638926 1.26651519 0.71569736 1.39968689 0.37590755 0.19339258
 0.26433523 0.32269774 0.71123996 1.1029702 ]


7. Заменить максимальный элемент массива на ноль

In [ ]:
z = np.random.random(10)
maxim=np.argmax(z)
print(z)
z[maxim]=0
print(z)

[0.89523672 0.46303758 0.04632821 0.63727741 0.40306484 0.43232381
 0.78696936 0.47252383 0.64231223 0.02977329]
[0.         0.46303758 0.04632821 0.63727741 0.40306484 0.43232381
 0.78696936 0.47252383 0.64231223 0.02977329]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [6]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print(z)
print(i)
z += np.bincount(i, minlength=len(z))
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6 0 1 3 6 8 7 2 9 7 3 9 6 6 3 0 2 9 4 9]
[3. 2. 3. 4. 2. 1. 5. 3. 2. 5.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
z = np.array([1,2,3,4,5])
lens = 5 + (5 - 1) * 3
z1 = np.zeros(lens)
z1[::4] = z
print(z)
print(z1)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
print(z)
print(v)
x=z[np.abs(z-v).argmin()]
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
32.93279896602199
33


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```



*   dtype: int64;
*   dtype: float64. присутствует число с плавающей запятой (1.), поэтому все числа будут приведены к этому типу;
*  dtype: float128. Явно указанный тип массива – float128;
*  dtype: complex128.Явно указанный тип массива - complex128;
*  dtype: float64. Явно указанный тип массива – float64;
*  dtype: int64. Явно указанный тип массива - int64;
*  dtype: bool. Все целые числа будут преобразованы в логические значения;
*  dtype: str. Все целые числа будут преобразованы в строки
*  dtype: str. Поскольку в массиве присутствует строковое значение;
*  dtype: complex128. Поскольку в массиве присутствует комплексное число;



**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```



*   Вывод: 41. Берется массив строковых значений, к 1ому элементу добавляется строка со значением '1';
*   Вывод: True. Третий элемент первого массива = 0 = True, первый элемент второго массива = -4 = False. True or False = True;
*   Вывод: False. Третий элемент первого массива = 0 = True. Первый элемент второго массива = -4 = False. True and False = False
*   Вывод: 1. -1 элемент массива = True. Значение True принимает 1;
*   Вывод: ошибка. Комплексное число не может быть преобразовано в int64;
*   Вывод: 1j. Комплексное число преобразуется в строку;
*   Вывод: 333. Умножение строки - ее повторение n количество раз;






**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```





*   Результат: массив формы (3, 5), заполненный единицами;
*   Результат: массив формы (3, 5), заполненный значением 3.14.;
*   Результат:

```
array([0. , 0.25, 0.5 , 0.75, 1. ])
```


*   Результат:

```
array([[1, 0, 0],
          [0, 3, 0],
          [0, 0, 5]])
```

*   Результат: ошибка, функции не существует;
*   Результат: массив формы (3, 3) с случайными числами;
*   Результат: создает единичную матрицу размером 3x3, где элементы на главной диагонали равны единице, а остальные — нулю
*   Результат: создает массив формы (3,) с неинициализированными значениями



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```



*   3;
*   7;
*   array([4]) - срез первой строки и последнего элемента в столбце;
*   array([4, 8]) - срез первых двух строк и их последних элементов;
*   

```
array([[3, 5],
          [7, 6]])
```

*   array([6, 8])
*   array([7, 6, 8, 8])
*   array([7, 6, 8, 8])
*   

```
array([[3, 5, 2, 4],
          [7, 6, 8, 8],
          [1, 6, 7, 7]])
```
*   элементы с интервалом 2 по обеим осям:


```
 array([[3, 2],
           [1, 7]])
```
*   

```
 array([[3, 2],
           [1, 7]])
```


*   Реверс строк и столбцов, поэтому массив будет перевернут:


```
    array([[7, 6, 1],
           [8, 6, 7],
           [4, 2, 5]])
```





**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


Первая операция  разбивает массив по строкам (ось 0).Вторая операция с параметром axis=1 разбивает массив по столбцам (ось 1):


```
  [array([[0, 1, 2, 3],
           [4, 5, 6, 7]]),
    array([[ 8,  9, 10, 11],
           [12, 13, 14, 15]])]
           
    [array([[0, 1],
           [4, 5],
           [8, 9],
           [12, 13]]),
    array([[ 2, 3],
           [ 6, 7],
           [10, 11],
           [14, 15]])].
```



**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

При работе NumPy массивами производится поэлементное сложение, после чего создается новый массив, состоящий из суммы соответствующих элементов. При работе с обычными списками создается новый список с элементами, указанными при сложении:


```
[1, 2, 3, 3, 2, 1]
array([4, 4, 4])
```



**7**. Как в CodeLab измерить время выполнения кода?

Использование модуля time.


```
import time

start_time = time.time()
.....
end_time = time.time()
print(end_time - start_time)
```



**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```



*   63;
*   Сумма элементов по строкам: [14,29,21];
*   Сумма элементов по столбцам: [11,17,17,19];
*   Ошибка, т.к массив 3х4;
*   [14,29,21];
*   array([3,5,2,4]);
*   array([3,5,2,4]);





**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```



*   [False, False, False, True];
*   [True, True, False, False];
*   [1, 2];
*   [4];
*   [1,2,4];



**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

На уровне реализации массив фактически содержит один указатель на непрерывный блок данных. Список в языке Python же содержит указатель на блок указателей, каждый из которых, в свою очередь, указывает на целый объект языка Python, например, целое число. Преимущество такого списка состоит в его гибкости: раз каждый элемент списка — полномасштабная структура, содержащая как данные, так и информацию о типе, список можно заполнить данными любого требуемого типа. Массивам с фиксированным типом из библиотеки NumPy недостает этой гибкости, но они гораздо эффективнее хранят данные и работают с ними.