<a href="https://colab.research.google.com/github/Linkabli/dap-2024/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
import numpy as np
array = np.random.randint(0, 100, size=(10, 10))
minimum = np.min(array)
maximum = np.max(array)
print("Массив 10x10:")
print(array)
print(f"Минимум: {minimum}")
print(f"Максимум: {maximum}")

Массив 10x10:
[[16 85 11 68 65  8 84 74 77 71]
 [27 13 47 91  5 37 84  1 86 45]
 [37 24 31 40 51 90 81 72  0 24]
 [17 68 27  6 44 10 20 37  6 59]
 [44 93 97 18 61 94 64  4 41 21]
 [19 93 39 45 82  4 29 97  0 29]
 [70 18 32  2 24 83  4 42 46 96]
 [32 98 47 14 73 97 48 67 38 90]
 [63 80 20 31 74 58 55 31 48 16]
 [40 96  4 79 64 24 79 53 78 48]]
Минимум: 0
Максимум: 98


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:
import numpy as np
matrix = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            matrix[i, j] = 1
print("8x8 матрица в шахматном порядке:")
print(matrix)

8x8 матрица в шахматном порядке:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
import numpy as np
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
import numpy as np
z = np.random.rand(5, 10)
print("Исходная матрица z:")
print(z)
mean_values = np.mean(z, axis=1)
z_centered = z - mean_values[:, np.newaxis]
print("\nМатрица после вычитания среднего значения из каждой строки:")
print(z_centered)

Исходная матрица z:
[[0.1038213  0.90392238 0.73679539 0.19701769 0.71230088 0.2888992
  0.79325602 0.83581083 0.30859368 0.32383054]
 [0.05643312 0.42504648 0.96635718 0.75739255 0.5387011  0.48164344
  0.13556215 0.8344429  0.15533322 0.61627959]
 [0.20692247 0.9011636  0.16290527 0.8077508  0.90701631 0.77821676
  0.1417396  0.52415583 0.44178    0.17745306]
 [0.7987466  0.98872375 0.62183385 0.15893885 0.69415538 0.25812609
  0.10111843 0.33641332 0.4573969  0.28057297]
 [0.6823537  0.22463348 0.0791118  0.26754613 0.21073195 0.26324102
  0.41570355 0.04449349 0.90924038 0.05269057]]

Матрица после вычитания среднего значения из каждой строки:
[[-0.41660349  0.38349759  0.2163706  -0.3234071   0.19187609 -0.23152559
   0.27283123  0.31538604 -0.21183111 -0.19659425]
 [-0.44028605 -0.07167269  0.46963801  0.26067337  0.04198193 -0.01507573
  -0.36115702  0.33772372 -0.34138595  0.11956042]
 [-0.2979879   0.39625323 -0.3420051   0.30284043  0.40210594  0.27330639
  -0.36317077  0.019

5. Поменяйте 1 и 2 строки матрицы

In [ ]:
import numpy as np
z = np.arange(25).reshape(5, 5)
print("Исходная матрица z:")
print(z)
z[[0, 1]] = z[[1, 0]]
print("\nМатрица после замены 1 и 2 строк:")
print(z)

Исходная матрица z:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Матрица после замены 1 и 2 строк:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
import numpy as np
z = np.random.random((10, 2))
print("Исходные декартовы координаты (x, y):")
print(z)
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coordinates = np.column_stack((r, theta))
print("\nПолярные координаты (r, θ):")
print(polar_coordinates)

Исходные декартовы координаты (x, y):
[[0.12749807 0.80863496]
 [0.41792753 0.54987919]
 [0.09224834 0.57131374]
 [0.4590134  0.65777152]
 [0.95286402 0.72222698]
 [0.24267479 0.70936615]
 [0.91530036 0.89967516]
 [0.95948551 0.254876  ]
 [0.23924876 0.67425665]
 [0.04501152 0.88727701]]

Полярные координаты (r, θ):
[[0.81862461 1.41441301]
 [0.69067398 0.92090357]
 [0.57871335 1.41071097]
 [0.80209517 0.96152751]
 [1.19564278 0.64857219]
 [0.74972754 1.24117583]
 [1.28342906 0.77678933]
 [0.9927609  0.25964196]
 [0.71544532 1.22982212]
 [0.88841799 1.52010982]]


7. Заменить максимальный элемент массива на ноль

In [ ]:
import numpy as np
z = np.random.random(10)
print("Исходный массив z:")
print(z)
max_index = np.argmax(z)
z[max_index] = 0
print("\nМассив после замены максимального элемента на 0:")
print(z)

Исходный массив z:
[0.97574339 0.87492617 0.1384516  0.46826946 0.79080477 0.96578903
 0.19172649 0.29004732 0.09989528 0.10924947]

Массив после замены максимального элемента на 0:
[0.         0.87492617 0.1384516  0.46826946 0.79080477 0.96578903
 0.19172649 0.29004732 0.09989528 0.10924947]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
print("Исходный массив:")
print(z)
print("\nИндексы инкремента:")
print(i)
z[i] += 1
print("\nГотовый массив:")
print(z)

Original array:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Indices to be incremented:
[2 6 1 1 2 3 5 4 9 2 5 6 9 9 7 9 9 3 7 4]

Array after incrementing:
[1. 2. 2. 2. 2. 2. 2. 2. 1. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [1]:
import numpy as np
z = np.array([1, 2, 3, 4, 5])
print("Исходный вектор:")
print(z)
new_vector = np.zeros(len(z) + (len(z) - 1) * 3, dtype=z.dtype)
new_vector[::4] = z
print("\nНовый вектор с тремя нулями между каждым значением:")
print(new_vector)

Исходный вектор:
[1 2 3 4 5]

Новый вектор с тремя нулями между каждым значением:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0, 100)
print("Случайное число v:", v)
closest_value = z[np.abs(z - v).argmin()]
print("Ближайшее значение в массиве z:", closest_value)

Случайное число v: 13.419337890991656
Ближайшее значение в массиве z: 13


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?

np.array([1, 4, 2, 5, 3]) = int64 (NumPy автоматически выберет int64 для целых чисел)
np.array([1., 4, 2, 5, 3]) = float64 (преобразование к float64 из-за наличия числа с плавающей точкой)

np.array([1, 4, 2, 5, 3], dtype='float128') = float128 (явное указание float128)

np.array([1., 4, 2, 5, 3], dtype='complex128') = complex128 (преобразование к комплексным числам с complex128)

np.array([1, 4, 2, 5, 3], dtype='float64') = float64 (явное указание float64)

np.array([1, 4, 2, 5, 3], dtype=int64) = int64 (явное указание int64)

np.array([1, 4, 2, 5, 3], dtype='bool') = bool (0 преобразуется в False, остальные — в True)
np.array([1, 4, 2, 5, 3], dtype='str') = str (все элементы будут строками)

np.array([1, 4, 2, 5, '3']) = str (все элементы будут строками, так как один элемент строковый)
np.array([1, -4, 2, 0, 1j]) = complex128 (преобразование к complex128 из-за комплексного числа)

**2**. Что будет выведено в консоль и почему?  
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1' = '41' (второй элемент строки '4', плюс '1' дает '41')  
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1] = False (четвертый элемент — False, второй элемент — True)  
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1] = False (четвертый элемент False, что приводит к результату False)  
np.array([1, -4, 2, 0, True], dtype='int64')[-1] = 1 (значение True преобразуется в 1)  
np.array([1, -4, 2, 0, 1j], dtype='int64')[1] = Ошибка (нельзя преобразовать комплексное число к int64)  
np.array([1, -4, 2, 0, 1j], dtype='str')[-1] = '1j' (последний элемент преобразуется в строку '1j')  
np.array([1, 4, 2, 5, '3'])[-1] * 3 = '333' (последний элемент — строка '3', умноженная на 3, дает '333')  

**3**. Каков результат операции?

np.ones((3, 5), dtype=float) → 3x5 массив из единиц с float элементами  
np.full((3, 5), 3.14) → 3x5 массив из значений 3.14  
np.linspace(0, 1, 5) → массив из 5 элементов [0. , 0.25, 0.5 , 0.75, 1.]  
np.diag((1,3,5)) → 3x3 диагональная матрица с диагональными элементами 1, 3, 5  
np.smile((1,3,5)) → Ошибка (нет функции np.smile)  
np.random.random((3, 3)) → 3x3 массив со случайными значениями от 0 до 1  
np.eye(3) → 3x3 единичная матрица  
np.empty(3) → массив из трех элементов с неинициализированными значениями  



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

```
X[0,0] → 3
X[-1,-1] → 7
X[0:1,-1] → array([4])
X[0:2,-1] → array([4, 8])
X[0:2,0:2] → array([[3, 5], [7, 6]])
X[1,1:3] → array([6, 8])
X[1,:] → array([7, 6, 8, 8])
X[:,:] и X[:] → весь массив X
X[::2,::2] → array([[3, 2], [1, 7]])
X[0:3:2,0:3:2] → array([[3, 2], [1, 7]])
X[::-1,::-1] → X, отражённый по обеим осям array([[7, 7, 6, 1], [8, 8, 6, 7], [4, 2, 5, 3]])
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

```
np.split(grid, [2]) → разделит grid на две части по горизонтали (верхние 2 строки и нижние 2 строки)
np.split(grid, [2], axis=1) → разделит grid на две части по вертикали (левые 2 столбца и правые 2 столбца)
```


**6**. В чем различие между операциями?

```
[1, 2, 3] + [3, 2, 1] → [1, 2, 3, 3, 2, 1] (конкатенация списков)
np.array([1, 2, 3]) + np.array([3, 2, 1]) → array([4, 4, 4]) (побитовая операция сложения массивов)
```

**7**. Как в CodeLab измерить время выполнения кода?

import timeit
timeit.timeit('код_для_измерения', number=1000)
Или, используя %%time и %%timeit в ячейках Jupyter Notebook.

**8**. Дан массив X, каковы результаты операций?

```
np.sum(M) → сумма всех элементов в массиве M
np.sum(M, axis=1) → сумма элементов по строкам
np.sum(M, axis=0) → сумма элементов по столбцам
np.sum(M, axis=2) → Ошибка (M — двумерный массив)
np.sum(M, 1) → сумма элементов по строкам
sum(M) → суммирует строки поэлементно (результат — массив)
sum(M,1) → Ошибка (встроенная sum не поддерживает параметр axis)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3 → array([False, False, False, True])
X < 3 → array([True, True, False, False])
X[X < 3] → array([1, 2])
X[X > 3] → array([4])
X[X != 3] → array([1, 2, 4])
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

Массивы NumPy быстрее и эффективнее списков Python благодаря:

1. Однородности типа данных, что позволяет использовать более компактное хранение в памяти.
2. Векторизированным операциям, оптимизированным для быстрого выполнения на низком уровне (используется C/Fortran).
3. Поддержке параллельных вычислений.