<a href="https://colab.research.google.com/github/cherkashin-py/dap-2024/blob/main/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Лабораторная работа №3. NumPy**

Цель работы: Научиться основным элементам библиотеки NumPy и их применению в решении задач



Задача 1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [19]:
import numpy as np

# Создаем массив 10x10 со случайными значениями
array = np.random.randint(-50, 50, size=(10, 10))

# Находим минимум и максимум
min_value = np.min(array)
max_value = np.max(array)

print("Массив 10x10:\n", array)
print("Минимальное значение:", min_value)
print("Максимальное значение:", max_value)

Массив 10x10:
 [[-17  31 -35   7  18  40 -34  -7  34 -38]
 [-11  -5  46  32 -10  16 -47 -44 -17  48]
 [-28 -14  44  16  39  18  10 -12 -42 -41]
 [-26  25  42 -30  35 -20  40   8  43  27]
 [-45 -32  -6  -3   1 -21 -42 -26  16 -31]
 [ 35  12  -3  45   9  -3  31 -23 -26  16]
 [-15 -45  19  17  45 -28  36  31   7  40]
 [  2 -28  25   0   2 -22  46  31  22 -24]
 [-21 -17  32  39  12  -7   5  32   8 -42]
 [-34  11 -10  31 -21  22 -21  30 -41  37]]
Минимальное значение: -47
Максимальное значение: 48


Задача 2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [5]:
import numpy as np

# Создаем 8x8 матрицу и заполняем ее в шахматном порядке
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1  # Заполняем единицами на четных столбцах для нечетных строк
chessboard[::2, 1::2] = 1  # Заполняем единицами на нечетных столбцах для четных строк

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задача 3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [21]:
import numpy as np

z = np.arange(11)
print("Исходный массив:", z)
z[(z > 3) & (z < 8)] *= -1
print("Измененный массив:", z)

Исходный массив: [ 0  1  2  3  4  5  6  7  8  9 10]
Измененный массив: [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


Задача 4. Найти среднее заначение строки матрицы и вычесть его из каждого элемента строки

In [23]:
import numpy as np

z = np.random.randint(0, 100, size=(5, 10))
print("Исходная матрица:\n", z)

# Находим среднее значение каждой строки
row_means = np.mean(z, axis=1)

# Вычитаем среднее значение из каждой строки
adjusted_z = z - row_means[:, np.newaxis]

print("Матрица после вычитания среднего значения:\n", adjusted_z)


Исходная матрица:
 [[56 88 94 65 41 32 50 55 94 63]
 [69 58 10 78 71 68 45 12 37 61]
 [31 94 76 69  1 47 86 18 85 11]
 [14 29 12 20 32 82  5 94 98 71]
 [ 5 96  8  3  0  9 32 33 97 23]]
Матрица после вычитания среднего значения:
 [[ -7.8  24.2  30.2   1.2 -22.8 -31.8 -13.8  -8.8  30.2  -0.8]
 [ 18.1   7.1 -40.9  27.1  20.1  17.1  -5.9 -38.9 -13.9  10.1]
 [-20.8  42.2  24.2  17.2 -50.8  -4.8  34.2 -33.8  33.2 -40.8]
 [-31.7 -16.7 -33.7 -25.7 -13.7  36.3 -40.7  48.3  52.3  25.3]
 [-25.6  65.4 -22.6 -27.6 -30.6 -21.6   1.4   2.4  66.4  -7.6]]


Задача 5. Поменяйте 1 и 2 строки матрицы

In [25]:
import numpy as np

z = np.arange(25).reshape(5, 5)
print("Исходная матрица:\n", z)

# Меняем 1-ю и 2-ю строки местами
z[[0, 1]] = z[[1, 0]]
print("Матрица после замены строк:\n", z)


Исходная матрица:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Матрица после замены строк:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Задача 6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [27]:
import numpy as np

z = np.random.randint(0, 100, size=(10, 2))
print("Декартовые координаты:\n", z)

# Преобразуем в полярные координаты
r = np.sqrt(z[:, 0]**2 + z[:, 1]**2)  # Радиус
theta = np.arctan2(z[:, 1], z[:, 0])  # Угол в радианах

# Собираем полярные координаты в один массив
polar_coordinates = np.column_stack((r, theta))

print("Полярные координаты (радиус, угол):\n", polar_coordinates)


Декартовые координаты:
 [[72 61]
 [21 44]
 [49 41]
 [11 93]
 [31 10]
 [74 92]
 [31  3]
 [55  8]
 [77 43]
 [73 71]]
Полярные координаты (радиус, угол):
 [[9.43663075e+01 7.02879209e-01]
 [4.87544870e+01 1.12549528e+00]
 [6.38905314e+01 6.96742282e-01]
 [9.36482781e+01 1.45306375e+00]
 [3.25729949e+01 3.12042122e-01]
 [1.18067777e+02 8.93409888e-01]
 [3.11448230e+01 9.64737752e-02]
 [5.55787729e+01 1.44441578e-01]
 [8.81929702e+01 5.09301144e-01]
 [1.01833197e+02 7.71510167e-01]]


Задача 7. Заменить максимальный элемент массива на ноль

In [29]:
import numpy as np

z = np.random.randint(0, 100, size=10)
print("Исходный массив:", z)
max_index = np.argmax(z)
z[max_index] = 0

print("Измененный массив:", z)


Исходный массив: [85 20 42 57 56 89 40 93 15 68]
Измененный массив: [85 20 42 57 56 89 40  0 15 68]


Задача 8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [32]:
import numpy as np

z = np.ones(10)
print("Исходный массив:", z)

# Генерация массива индексов
i = np.random.randint(0, len(z), 20)
print("Сгенерированные индексы:", i)

# Получаем уникальные индексы
unique_indices = np.unique(i)

# Добавляем 1 к элементам по уникальным индексам
z[unique_indices] += 1
print("Измененный массив:", z)


Исходный массив: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Сгенерированные индексы: [3 4 3 4 2 0 5 3 6 2 2 3 0 2 2 3 2 5 8 5]
Измененный массив: [2. 1. 2. 2. 2. 2. 2. 1. 2. 1.]


Задача 9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [33]:
import numpy as np

z = np.array([1, 2, 3, 4, 5])

# Создаем новый вектор с тремя нулями между каждым значением
new_length = len(z) + (len(z) - 1) * 3  # Длина нового вектора
new_vector = np.zeros(new_length)         # Создаем массив нулей

# Заполняем новый вектор значениями из исходного
new_vector[::4] = z  # Каждое 4-е значение - это элемент из z

print("Новый вектор:", new_vector)


Новый вектор: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Задача 10. Найти ближайшее к заданному значению число в заданном массиве

In [40]:
import numpy as np

z = np.arange(100)

# Генерируем случайное число в диапазоне от 0 до 100
v = np.random.uniform(0, 100)

print("Заданное число:", v)

# Находим индекс ближайшего числа в массиве z
index = np.argmin(np.abs(z - v))

# Находим ближайшее значение
closest_value = z[index]

print("Ближайшее число в массиве:", closest_value)


Заданное число: 51.60688031714577
Ближайшее число в массиве: 52


# **Вывод:**
Были изученые основные элементы библиотеки NumPy и их применение в решении задач